### ISSUE TITLE
Suggestions: Client Version Spoof, NBT chests, and Plugin list

### ISSUE THREAD

**Issue by ElmoPog** [TaxEvasiqn/allah-hack#3]
### **Suggestion 1:**

> It would be nice to have an option to Spoof the version of your Client so you can join without the need of servers having ViaVersion enabled.

### **Suggestion 2:**

> NBT Items. There is already a Meteor client which does this but their 'NBT chest' does not have any NBT thus making it useless. Would be cool if you could add such a feature to the Addon.

### **Suggestion 3:**

>Server Plugin list. Impact client has a Feature to show a server's Plugin list. Would be cool if you could do that

Thanks for reading :)

**Comment by TaxEvasiqn** [comment]
1) use viafabric to join older servers (its 6mb so im not pasting into this)
2) maybe!
3) .server plugins (might be rejects or default meteor cant remember)
