### ISSUE TITLE
Insta eat 

### ISSUE THREAD

**Issue by 60YzArC** [TaxEvasiqn/allah-hack#4]
:p 

yes

**Comment by I-Got-You-Dead** [comment]
How

**Comment by TaxEvasiqn** [comment]
i fucking love this!!!!!!!!!
https://open.spotify.com/track/1uNePI826aqh9uC9pgbeHU

**Comment by dr-fancy-pants** [comment]
you cant instantly eat a consumable??? (if there is a hack that can do this please show me, i have never seen this before)

**Comment by TaxEvasiqn** [comment]
i can't really find a way but i'm pretty sure you can use timer to eat it faster
