### ISSUE TITLE
Auto Farm Module

### ISSUE THREAD

**Issue by mrGRINCH** [TaxEvasiqn/allah-hack#6]
Can you add the Auto Farm module from bleach hack please.

**Comment by I-Got-You-Dead** [comment]
Ong it’s in baritone

**Comment by mrGRINCH** [comment]
No it's not. The one in Baritone is different.

**Comment by mrGRINCH** [comment]
It's twenty times slower.

Plus he literally asked for people to open issues if they want anything added. If he doesn't want to add it that's fine but there's no reason I can't ask.

**Comment by I-Got-You-Dead** [comment]
> It's twenty times slower.
> 
> Plus he literally asked for people to open issues if they want anything added. If he doesn't want to add it that's fine but there's no reason I can't ask.

Cope

**Comment by TaxEvasiqn** [comment]
[you really want to farm don't you](https://github.com/AntiCope/meteor-rejects/issues/80)

**Comment by mrGRINCH** [comment]
> [you really want to farm don't you](https://github.com/AntiCope/meteor-rejects/issues/80)

Lol. More just a convenience kinda thing.

**Comment by TaxEvasiqn** [comment]
soon!
